# Uncomment the next line to define a global platform for your project

# platform :ios, '9.0'
target 'newmyfood' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for newmyfood
 pod 'Alamofire', '~> 4.5'
 pod 'SwiftyJSON'
pod 'Firebase/Core'
pod 'Firebase/DynamicLinks' 
pod 'Firebase/Messaging'





  target 'newmyfoodTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'newmyfoodUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
